### ISSUE TITLE
ModuleNotFoundError on v0.13.1

### ISSUE THREAD

**Issue by thatnerdnoah** [toontown-archipelago/toontown-archipelago#182]
Experienced the following error when running the server components from the built client on macOS. Based on discussions in the Discord server, it appears to be happening on Windows as well.

`ModuleNotFoundError: No module named 'websockets.legacy'`

**Comment by HiddenKitten** [comment]
quick possible solutions:

- pin requirements.txt versions to latest known working.

- Actually update our code to not use the deprecated implementation.

This issue should also happen on development clients if we were to run `pip install --upgrade -r requirements.txt`, it seems to have been removed in the latest update on pypi.

as far as I can see, we don't directly try to import websockets.legacy, so I'll quickly look to see if I can track down where it tries to be imported from.

**Comment by HiddenKitten** [comment]
alright looking further in, they removed InvalidMessage - because it wasn't used in their new asyncio implementation.

... they forgot it was used in the threading implementation, and reimplemented it 2 weeks ago, but never put a new release out.

so: pinning an old version is actually the fix here.

**Comment by DarthMDev** [comment]
Should be resolved now feel free to reopen if we find its still not working
